### ISSUE TITLE
WordPress 3.3.1 - Response from server does not contain valid XML

### ISSUE THREAD

**Issue by Ascott03** [alexjamesbrown/JoeBlogs#12]
I get the exception at the bottom of this message when I make a call to either GetUserInfo, GetCategories, GetAuthors on both the classes WordPressWrapper and MetaWeblogWrapper.

 try
 {
    WordPressWrapper wp = new WordPressWrapper(siteURL, username, password);
     IList authors = wp.GetAuthors();

```
 foreach(Author a in authors)
 {
      Console.WriteLine("User Name:       {0}", a.user_id);
      Console.WriteLine("User Login:        {0}", a.user_login);
     Console.WriteLine("Display Name:  {0}", a.display_name);
}
```

  }
 catch (Exception ex3)
 {
     throw new Exception("Failed to retrieve author information.", ex3);
 }

 System.Exception: Failed to retrieve author information. ---&gt; CookComputing.XmlRpc.XmlRpcIllFormedXmlException: Response from server does not contain valid XML.---&gt; System.Xml.XmlException: Reference to undeclared entity 'raquo'. Line 25,position 78.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.HandleGeneralEntityReference(String name, Boolean isInAttributeValue, Boolean pushFakeEntityIfNullResolver, Int32 entityStartLinePos)
   at System.Xml.XmlTextReaderImpl.HandleEntityReference(Boolean isInAttributeValue, EntityExpandType expandType, Int32&amp; charRefEndPos)
   at System.Xml.XmlTextReaderImpl.ParseAttributeValueSlow(Int32 curPos, Char quoteChar, NodeData attr)
   at System.Xml.XmlTextReaderImpl.ParseAttributes()
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
   at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.Load(Stream inStream)
   at CookComputing.XmlRpc.XmlRpcSerializer.DeserializeResponse(Stream stm, Type svcType)
   --- End of inner exception stack trace ---

**Comment by Ascott03** [comment]
I got around this this issue by replacing the CookComputing.XmlRpcV2  DLL that comes with the binaries from CodePlex (i.e. v.2.3.2) with version 2.5.0.

Note, this may no longer be a issue as the source from this site is using CookComputing.XmlRpcV2 version 2.5.0.

**Comment by alexjamesbrown** [comment]
Sorry for taking 4 months to reply...

Any chance you could fork this and update?
Will merge your changes in?

V. Keen to grow this project

**Comment by GarethWright** [comment]
You may also get this if you have been reading xmlrpc tutorials on the web, which I did before finding this.

They incorrectly specify the URL as http://[url]/wordpress/xmlprc.php 
Not everyone installs wordpress in a subfolder called wordpress.

URL using this wrapper must be the the full path to xmlrpc.php

**Comment by alexjamesbrown** [comment]
Ahh ok...
hmm.. i can't tell from the stack trace of the OP if this is the case though?

**Comment by GarethWright** [comment]
Perhaps its worth adding a standard http request object to check that the
URL is valid http 200 response?

**Comment by alexjamesbrown** [comment]
Good idea...
I'll try and get that implemented...

Feel free to do it & create a pull request if you have time ;-)

**Comment by GarethWright** [comment]
I'll try get to that tomorrow.
Need to figure out how to create a new post with featured image and custom
fields first.

:)

**Comment by alexjamesbrown** [comment]
Cool!
Just created #17 to handle featured image...

**Comment by GarethWright** [comment]
Magic.
Really outstanding project.
Can't wait to show finish off the new blog admin tool :)
